### ISSUE TITLE
indentation suggestion

### ISSUE THREAD

**Issue by curist** [janet-lang/janet.vim#1]
Howdy, is it possible to indent loop keywords aligned in the same column? i find it looks better
```clojure
  (loop [i :in (range buf-size)
           :until (= ("R" 0) (get buf (dec i)))]
    (:read stdin 1 buf))
```

**Comment by bakpakin** [comment]
Most of the indentation code was taken from vim-clojure-static, and then tweaked until it looked good. I would have to to do a dive into the code but I’m not sure it would be easy.

**Comment by curist** [comment]
Cool, at least I know you find this style pleasant to look at. The indent script is quite nontrivial to me, so I'm afraid of I can't do much on this one.

**Comment by curist** [comment]
I think I will try to add JanetLoop as a region, and then match first `[ ]` block as JanetLoopHead, and then we will be able to check if we are in a JanetLoopHead region in the indent script, and do things correspondingly. I will try to take a stab at this, but it may take a while.

**Comment by bakpakin** [comment]
Noticed there are some issues with the new indentation.

Proper indentation (old)
```clojure
(loop [x :range [0 10]
       y :range [0 100]]
  (print x ", " y))
```
New indentation
```clojure
(loop [x :range [0 10]
         y :range [0 100]]
  (print x ", " y))
```

The problem is that the syntax is pretty free form, you can't just assume that the second line is a modifier. I might favor the old indentation as while not as pleasing in some cases, it is at least regular and predictable.

**Comment by curist** [comment]
Aww, didn't catch this case. Please feel free to revert the merge. I think I can handle this case, because we can differentiate the :verb from the :modifiers.

**Comment by curist** [comment]
maybe simply remove loop verbs from JanetLoopKeywords will do? I will try it later.

edit. shoot, I'm confusing myself

**Comment by bakpakin** [comment]
I'm going to revert everything back. Feel free to reopen the PR. My bad, I should have done some preliminary checks before merging.

**Comment by curist** [comment]
So, it will be more like, we should only indent a modifier align to previous line's verb.
But we won't be able to know that when entering a new line, if it's going to be a modifier or not.
If we indent right after we detect a modifier, the typing experience won't feel too great.

**Comment by curist** [comment]
> I'm going to revert everything back. Feel free to reopen the PR. My bad, I should have done some preliminary checks before merging.

My bad :sob:
