### ISSUE TITLE
janet.vim cannot correctly indent a function with a long documentation.

### ISSUE THREAD

**Issue by amano-kenji** [janet-lang/janet.vim#14]
I don't exactly know what breaks janet.vim indentation.

If I try to indent `j3blocks/run` on https://codeberg.org/amano.kenji/j3blocks with janet.vim, janet.vim breaks indentation.

**Comment by sogaiu** [comment]
As code might change going forward, I'll put what looks to be the current version (commit: 2fe3f426) of what I understand `j3blocks/run` below:

<pre>
(defn run
  ````
  A unix domain stream socket will be created at `$XDG_RUNTIME_DIR/j3blocks/unix-socket-name` or
  /tmp/j3blocks/$UID/unix-socket-name

  blocks is a list of blocks.

  A block is a struct that has the following keys.

      {:id "name" or ["name" "instance"]
       :module {:event fn :output fn}
       :user-event fn
       :user-output fn
      }

  * `:id` - either "name" or `["name" "instance"]`. It should be unique among the list of given blocks. It is used
    identify clicks and unix domain socket messages.
  * `:module` - It is a struct returned by a j3blocks module.
  * `:user-event` - an optional function
  * `:user-output` - an optional function

  module event fnction receives events from the input channel and sends only relevant events to the output channel.
  Events passed to module event function's output channel are passed to module output function's input channel.
  The simplest module event function has the following form.

      (fn
        [in out]
        (forever
          (ev/give out (ev/take in))))

  This passes every event from j3blocks to module output function's input channel.

      (fn
        [in out]
        (forever (ev/take in)))

  This drops every event from j3blocks.

  Module event function can filter j3blocks events and also add its own events to module output function.

  Events passed to module event function's input channel are

      {:type "click"
       :data click-event-json-object-from-swaybar-or-i3bar
      }

  Note: Refer to swaybar protocol or i3bar protocol for details.

      {:type "message"
       :data any-json-data-sent-by-j3blocks/msg function
      }

  `:user_event` is a function of the following form.

      (fn
        [in out]
        (forever (ev/give out (ev/take in))))

  user event function accepts events from module event function through input channel and can selectively pass those
  events to module output function through its output channel. It can also inject its own events to module output
  function.

  If module event function or user event function doesn't take events from input channels, j3blocks will be forced to
  stop sending events to module event function's input channel because it cannot accept new events.

  Module output function runs on a separate thread and has the following form.

      (fn
        [in out]
        (forever
          (try
            (do
              (ev/with-deadline 3 (ev/take in))
              (ev/give out @{"full_text" "An event occurred."})))
            ([err]
             (ev/give
               out
               @{"full_text" "No event occurred for 3 seconds."}))))

  module output function accepts events from module event function or user event function through input channel and
  should output a mutable block object table recognized by i3bar or swaybar. At the minimum, `full_text` is required.
  If nil is output, then the block disappears. module output function should not take events from input channel if
  there is no event to process.

  If module output function writes a static text to a block only once, then it's okay to write a static text to a block
  once and exit as below.

      (fn
        [in out]
        (ev/give out @{"full_text" "block text"}))

  Note: module output function should output a mutable table instead of an immutable struct because users will often
  modify its output with user output function.

  If module output function doesn't take incoming events from input channel, then events from module event function or
  user event function will be dropped.

  `:user_output` is a function that accepts module output function's output through its input channel and processes it
  and outputs a block recognized by i3bar or swaybar through its output channel. user output function runs on the same
  thread as module output function. The function has the following form.

      (fn
        [in out]
        (forever
          (ev/give out (put (ev/take in) "separator" true))))

  This user output function sets separator to true in the block given by module output function.

  If module output function writes a block only once, then user output function can also write a block only once and
  exit as below.

      (fn
        [in out]
        (ev/give out (put (ev/take in) "separator" true)))

  If both module output function and user output function exit, the thread that runs these functions will be closed.

  Refer to swaybar protocol or i3bar protocol for details.

  "name" and "instance" properties returned from module output function or user output function will be ignored
  because each block :id already sets name and instance.
  ````
  [unix-socket-name & blocks]
  (print (json/encode {"version" 1 "click_events" true}))
  (print "[")
  (let [events (ev/chan 20)
        click-events (ev/thread-chan 10)
        update-block (ev/chan 10)
        block-events (create-block-event-channels update-block blocks)]
    # send messages on unix domain stream socket to events channel
    (ev/spawn
      # Create directory for unix socket
      (def unix-socket-path (path/join unix-socket-dir unix-socket-name))
      (sh/create-dirs unix-socket-dir)
      (os/chmod unix-socket-dir 8r700)
      # clean up the unix domain socket from previous runs.
      (sh/rm unix-socket-path)
      # Listen to a unix socket
      (def server (net/listen :unix unix-socket-path :stream))
      # Process unix socket messages
      (defer (os/rm unix-socket-path)
        (forever
          (let [conn (net/accept server)
                recv (msg/make-recv conn json/decode)]
            (ev/spawn
              (defer (:close conn)
                (def {"id" id "message" msg} (recv))
                (when (not (ev/full events))
                  (ev/give events {:type "message" :id id :data msg}))))))))
    # send click events from standard input to events channel
    # Because file/read blocks the event loop, it has to be executed in a separate thread.
    (ev/spawn-thread
      (forever
        (ev/give click-events {:type "click" :data (json/decode (file/read stdin :line))})))
    (ev/spawn
      (forever
        (def click-event (ev/take click-events))
        (when (not (ev/full events))
          (ev/give events click-event))))
    # route events to blocks
    (ev/spawn
      (forever
        (def event (ev/take events))
        (case (get event :type)
          "click"
          (when-let [id (match (get event :data)
                          {"name" name "instance" instance}
                          [name instance]
                          {"name" name}
                          name)
                     block-event (get block-events id)]
            (when (not (ev/full block-event))
              (ev/give block-event event)))
          "message"
          (when-let [id (get event :id)
                     block-event (get block-events id)]
            (when (not (ev/full block-event))
              (ev/give block-event {:type "message" :data (get event :data)}))))))
    # update blocks, and print them
    (let [block-outputs (reduce (fn
                                  [acc {:id id}]
                                  (array/push acc {:id id :output nil}))
                                @[]
                                blocks)]
      (forever
        (def [idx block] (ev/take update-block))
        (def {:id id} (get block-outputs idx))
        (put block-outputs idx {:id id :output block})
        (print (json/encode (map
                              (fn [{:id id :output block}]
                                (def b (if (nil? block)
                                         @{}
                                         block))
                                (put b "name" nil)
                                (put b "instance" nil)
                                (match id
                                  [name instance] (do
                                                    (put b "name" name)
                                                    (put b "instance" instance))
                                  _ (put b "name" id)))
                              block-outputs)))))))
</pre>

**Comment by sogaiu** [comment]
I don't know how to reproduce the issue.

Any hints?

**Comment by amano-kenji** [comment]
Press `==` on the line `(print "[")` or the line above it.

**Comment by sogaiu** [comment]
Thanks for the hint.

You might find [this](https://github.com/janet-lang/janet.vim/pull/13) to be of interest.

When I did:

```
:setlocal lisp
```

behavior seems to be improved at least on the lines you mentioned.

**Comment by amano-kenji** [comment]
`:setlocal lisp` seems to fix this issue. The fact that it is still not merged is criminal.

**Comment by sogaiu** [comment]
Time to relax a bit perhaps?

People have lives outside of coding I think (^^;

**Comment by sogaiu** [comment]
@amano-kenji #13 has been merged.

Perhaps this issue can be closed?

**Comment by amano-kenji** [comment]
:cat2:
